<?php
/* Smarty version 3.1.32-dev-38, created on 2018-03-10 02:05:26
  from 'c:\vhosts\lovegolf\templates\modules\privacy.tpl' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.32-dev-38',
  'unifunc' => 'content_5aa33d66544460_64591577',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    'e0b29957e9b79c3fd48f8206e2fc2c4bea259ebe' => 
    array (
      0 => 'c:\\vhosts\\lovegolf\\templates\\modules\\privacy.tpl',
      1 => 1403646462,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_5aa33d66544460_64591577 (Smarty_Internal_Template $_smarty_tpl) {
?>
			<div class="moduleArea">
				
				<h1>Privacy</h1>
			    <p><?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 is registered with The Data Protection Authorities and is committed to protecting your right to privacy arising from your use of its website. This policy is to cover any use which <?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 may make or any information you provide to <?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 when using any part of the <?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 website.</p>
				<p>&nbsp;</p>
				<p>The only information which <?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 collects about you is the information which you put into the Site when using it. In order to use the Site you will have entered your name and your E-mail address. In the course of using the Site you will have entered details of Golf Courses you have played and the scores you have obtained when playing them, together with other information about your performance on the Golf Courses in question. If you have entered any competitions you may have provided to us such things as your postal address and telephone numbers.</p>
				<p>&nbsp;</p>
				<p>The information you provide to us is held on computers owned by us or contracted to us, and such computers may be outside United Kingdom. The information is collected solely to enable you to use the Site or for the other purposes specifically notified to you when you are requested to provide the information in question. No information provided to us or generated by us from it about you will be provided to any other person without your specific prior approval.</p>
				<p>&nbsp;</p>
				<p>In order that the Site is able to recognise you when you re-visit it and show you information about yourself, we may use a "Cookie", which is a small text file which is stored on your computer while you are in contact with the Site in order to provide the service to you. No information will be passed to any person by virtue of the existence of the "Cookie" on your computer.</p>
				<p>&nbsp;</p>
				<p>If you cease to be entitled to use <?php echo $_smarty_tpl->tpl_vars['domain']->value['pagetitle'];?>
 your information will be retained for one month only and then deleted. No information so deleted will be available to you or to any other person after it is deleted.</p>
				<p>&nbsp;</p>
				<p>If you have any questions or complaints about the use of personal information you may address those to us by E-mail - <?php echo '<script'; ?>
 type="text/javascript">email("privacy", "lovegolf", "co.uk")<?php echo '</script'; ?>
>. We reserve the right to change this policy from time to time and if any changes are made a notice will be placed on the website where you will also find this policy in its current terms.</p>
				<p>&nbsp;</p>
				<p>Other websites may be identified on the Site and links to those websites may be provided. They are provided for information only and we accept no responsibility for anything arising from your access to such websites or any material which they may contain.</p>
			</div>
<?php }
}
