<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.
eval(base64_decode('Pz48P3BocA0Kc3dpdGNoKCRZS3lRQzEzMEEpew0KY2FzZSAnZ3onOg0KJG81OU9EaHFWMyA9IGQwaTJjY0NPcShGYWh1TU92bEVVWi4nc2l0ZW1hcC54bWwnKTsNCkU4RTZoN1hOb0p5YWJBKCdzaXRlbWFwLnhtbCcsICRvNTlPRGhxVjMsIEZhaHVNT3ZsRVVaLCB0cnVlKTsNCmJyZWFrOw0KfQ0KPz4='));
?>