<h1>Terms and Conditions of Use</h1>
<p>This website is operated by lovegolf.co.uk (referred to as "Love Golf/lovegolf.co.uk/we/our/us"). As user of this website (referred to as "you/your") you acknowledge that any use of this website including any transactions you make ("use/using") is subject to our terms and conditions below.</p>
<p>&nbsp;</p>
<p>Please:</p>
<p>&nbsp;</p>
<ul class="termsList">
	<li>read through these terms and conditions carefully before using this website</li>
	<li>print a copy for future reference</li>
	<li>also read our Privacy section regarding your personal information</li>
</ul>
<p>&nbsp;</p>
		  	  	<p>STANDARD TERMS AND CONDITIONS for {$domain.pagetitle} - 2010 EDITION</p>
				<p>&nbsp;</p>
				<p>Whenever you log on to this site, by using the site you agree that these conditions of dealing apply to what you do and {$domain.pagetitle} does, and that there is a contract between us on these terms. Your statutory rights are not affected. {$domain.pagetitle}'s privacy policy applies to this contract.</p>
				<p>&nbsp;</p>
				<p><strong>Defining terms</strong></p>
				<p>In these conditions unless it is obvious that they have some other meaning, the "site" means the website called {$domain.pagetitle}, the word "we" means {$domain.pagetitle}, the word "you" means the person who logged onto the site and caused any relevant fee to be paid and other words have their usual meaning except where they are referred to on the site and given a definition there, which will then apply. Terms set out on the face of the site are incorporated in these terms and treated as part of them.</p>
				<p>&nbsp;</p>
				<p><strong>Nature of the site</strong></p>
				<p>{$domain.pagetitle} is an on-line entertainment facility for golfers to enter statistical information and have it processed in several different ways. They may then conveniently interpret it for any personal use they may wish. It provides for record-keeping and for statistical analysis of the records. We take all reasonable care to ensure that the output produced by {$domain.pagetitle} is a true reflection of the information put in by you as user. Neither we nor anyone on our behalf makes any claim or promise in relation to the effectiveness of the output of the site for any purpose other than providing statistical representation of information provided by you. The site is provided only on the basis that you will not use it for any purpose intended or primarily intended to confer on you any financial benefit. If you do use it for such a purpose we will not be liable for any loss you may suffer whether directly or indirectly.
				<p>&nbsp;</p>
				<p><strong>What you must do</strong></p>
				<p>If you use the site you must provide us with all the information needed to enable us to identify you whenever you log on and you are responsible for ensuring that that information is correct, that you have the right to enter it on the site, and that you keep confidential any of it which is not in your sole gift to use for the purpose. You are also responsible for making sure that your computer is not accessible by others in such a way that they can use the site without permission from us. You must keep our information - that is to say anything that we tell you only so that you can use the site - confidential, and keep your password secret so that it cannot be used by anyone other than yourself.</p>
				<p>&nbsp;</p>
				<p>You must take the earliest possible opportunity to confirm to your own satisfaction that we have carried out our obligations under these terms and notify us immediately if you find any reason to believe we have not done so.</p>
				<p>&nbsp;</p>
				<p>When you log on to the site you are communicating with us by electronic means and you must allow us to communicate with you by electronic means too. You must use the site only in accordance with these terms.</p>
				<p>&nbsp;</p>
				<p><strong>What we will do</strong></p>
				<p>We will take reasonable steps to provide access for you to the site and keep the site available to you and do so with proper skill and care and to the usual standards of the industry. Our honest and reasonable judgments in the provision of the facilities of the site will be the basis of what we do unless we have specifically agreed otherwise in writing. By accepting your payment we will give you as long as your payment is maintained a licence to use the site limited to the entering of your own information and the viewing and downloading of those parts of the site intended for viewing and downloading.</p>
				<p>&nbsp;</p>
				<p>We aim for high standards in all we do and will do what is reasonable to achieve them in providing the site. If we are properly notified of any defects in the site we will if they are the result of any error on our part put them right as soon as reasonably practicable. We will take proper reasonable steps to limit downtime of the site as far as within our control.</p>
				<p>&nbsp;</p>
				<p>We will retain the intellectual property rights in anything of ours which is on the site but give you any rights you need in order to enable you to use the site to its fullest potential under these terms. We will keep confidential all information we receive or learn from you in terms that render them confidential and will use it only for the purposes for which you provided it.</p>
				<p>&nbsp;</p>
				<p>We will perform our duties within our Privacy Policy for the time being as far as within our control.</p>
				<p>&nbsp;</p>
				<p><strong>What we will NOT do</strong></p>
				<p>We will not be bound to do anything which has not first been agreed by us in writing either at the outset or as the agreement has gone on. Except in relation to relevant personal injuries we will not accept liability for losses beyond the cost of what you have paid for the use of the site in accordance with this contract. We will not be liable to pay to you or anyone else (unless by law we are barred from excluding the liability or we have otherwise agreed in writing in advance) damages arising from any consequential losses (including but not limited to loss of profits) you or anyone else may suffer if we do not carry out our work or perform our obligations under the agreement in accordance with these conditions, even if such a loss might have been foreseeable to anyone knowing all relevant facts.</p>
				<p>&nbsp;</p>
				<p>We will not be bound to continue to give or allow you access to the site under this or any previous or subsequent agreement if you have not paid the appropriate fee in respect of the relevant period, even if there is an argument between you and us about the amount due.</p>
				<p>&nbsp;</p>
				<p>We will not be bound to continue to provide access to the site if you have failed or have yet to provide any required information or facility, or where the provision made by you has been incomplete or otherwise incorrect. We will not be responsible for advising you or anyone on your behalf of the suitability of the use of the site for any specific purpose to which you wish to put it.</p>
				<p>&nbsp;</p>
				<p>We will not be bound to continue to provide access to the site goods at any time when performance is impracticable because of outside forces entirely beyond our control including, for example, terrorist activity government prohibition riots strikes or other civil or international disorder. In particular we will not be liable for any cost or loss arising from access to the site not being available to you at any particular time. The nature of the world wide web is such that interruptions in availability are inevitable from time to time, and maintenance of the site also requires that access to it may be occasionally restricted or suspended for that purpose. We reserve the right to maintain the site and repair it at such times as we think best, having regard to all relevant interests.</p>
				<p>&nbsp;</p>
				<p><strong>What you must not do</strong></p>
				<p>You must not disclose to anyone other than for the necessary purposes the use of the site under these terms anything you learn about us or about the site or the techniques used by us to produce the site or any part of it unless either we authorise you to do so or the information is already public or becomes public before you disclose it.</p>
				<p>&nbsp;</p>
				<p>You must not seek to pass on to anyone else without our agreement any rights that you may have under these conditions.</p>
				<p>&nbsp;</p>
				<p>You must not use the site for any illegal immoral or improper purpose nor cause any damage to the site or any part of it.</p>
				<p>&nbsp;</p>
				<p><strong>General conditions</strong></p>
				<p>Except in relation to time of payment, time is not of the essence of any agreement made under these terms unless specifically so agreed in writing by you and us in advance.</p>
				<p>&nbsp;</p>
				<P>Payment of the fee entitles you to access to the site for the period to which the payment relates. Neither we nor you may terminate the agreement made under these terms before the expiry of that period unless the other is in relevant breach of these terms and has continued so fail even after being given notice of the breach and a reasonable time to remedy it.</p>
				<p>&nbsp;</p>
				<p>Neither you nor we will be bound to continue to waive any rights under any agreement made under these terms as a result of having waived or delayed enforcing those or any other rights in the course of its performance.</p>
				<p>&nbsp;</p>
				<p>Both you and we will abide by all statutes, regulations and similar legal obligations which relate either directly or indirectly to the performance or outcome of performance of any agreement made under these terms.</p>
				<p>&nbsp;</p>
				<p>Any agreement made under these terms is governed by English Law, the Interpretation Acts shall apply to it, it shall be construed as if they were a Statute, and it shall be subject to the jurisdiction of the courts of England and Wales, but no third party shall be entitled to the benefit of any term of any agreement made under these terms unless that entitlement arises other than by virtue of the provisions of the Agreements (Rights of Third Parties) Act 1999. These conditions and relevant parts of the site are the whole agreement between you and us unless we have written down a different agreement or amendment to it and signed that written record.</p>
<p>&nbsp;</p>
<ol>
	<li><strong>General</strong>
		<ol>
			<li>We reserve the right to change these terms and conditions at any time. Any such changes will take effect when posted on the website (see date at the top) and it is your responsibility to read the terms and conditions on each occasion you use this website and your continued use of the website shall signify your acceptance to be bound by the latest terms and conditions.</li>
			<li>If you are not a consumer, you confirm that you have authority to bind any business on whose behalf you use this website</li>
		</ol>
	</li>
	<li><strong>Order process</strong>
		<ol>
			<li>Please see How To Shop section for information on how to place an order. All orders that you place on this website will be subject to acceptance in accordance with these terms and conditions.</li>
			<li>The 'confirmation' stage sets out the final details of your order. Following this, we will send to you an order acknowledgement email. Please note that this email is not an order confirmation or order acceptance from Love Golf.</li>
			<li>Acceptance of your order and the completion of the contract between you and us will take place on despatch to you of the products ordered unless we have notified you that we do not accept your order or you have cancelled it (please refer to Guarantees and Returns Policy).</li>
			<li>We do not file details of your order for you to subsequently access direct on this website, and therefore, please print out these terms and conditions and the order acknowledgement for your own records. If you wish to obtain specific details of your previous orders please Contact Us.</li>
		</ol>
	</li>
	<li><strong>Delivery</strong>
		<ol>
			<li>All goods must be signed for by an adult aged 18 years or over on delivery.</li>
			<li>Delivery charges and estimated timescales are specified in Shipping section and also when you place an order. We make every effort to deliver goods within the estimated timescales, however delays are occasionally inevitable due to unforeseen factors. Love Golf shall be under no liability for any delay or failure to deliver the products within estimated timescales.</li>
			<li>Once a tracking number has been emailed to you (a copy is also available online in your account section), it is your responsibility to monitor and track the status of your parcel. If you notice any problems for example - Address Not Found, Failed Delivery, Recipient Absent etc then please contact us immediately so we can assist in resolving any problems. Failed-delivery parcels are normally held at a local depot for a maximum of five days before returning back to us. It is therefore your responsibility to contact us in good time to advise us of this situation in order to stop any return. We take no responsibility for parcels returned to us after successive delivery attempts and any return charges will be passed to you.</li>
			<li>If the package has not been accepted or rejected besides the valid reasons (see 3.3) during delivery, the respective courier will make a return charge to Love Golf. This charge will be required to be paid before processing a redelivery or will be retained if order has been cancelled.</li>
			<li>In the event where deliveries have failed due to incorrect address specified or if no one is available to accept delivery at time when courier attempts to deliver goods, the courier will hold the goods at their depot for a small period of time (anytime between 3-5 days). If a card has been left by the courier requesting you to contact them, you are requested to contact them to arrange a re-delivery at same address at a suitable time. Failure to do so quickly (normally within 2 working days) may cause the parcel to be returned back to us. Although every effort is made to ensure goods are delivered to you in good time and at address specified, certain circumstances may fail deliveries (for e.g. unable to find address or no one to accept parcel etc). In order to solve such problems during delivery or if you wish to advise us of change of delivery address after goods have been shipped, you are requested to contact us on first occasion. Normally a charge is incurred for amendments of delivery addresses which can be accepted by yourself or you may simply arrange to collect the goods from the courier depot where possible without any charges. Failure to do so or if you advise a change of address directly with the courier without notifying us will incur an additional charge which will be passed on to you unless we have already authorised this change with the courier.</li>
			<li>Upon delivery it is your responsibility to check package and its contents thoroughly. If you notice any signs of security tape damage, theft or attempt for theft, damage of goods or any unacceptable condition of package and its contents you are requested not to accept the package. If you are willing to accept the package then you are requested to sign on the delivery note what you have noticed for e.g. Goods Damaged or Theft Attempt etc. FAILURE to comply with these terms will NOT enable you to make any claims against the above conditions and NO credit will be issued.</li>
			<li>Risk of loss and damage of products passes to you on the date when the products are delivered or on the date of first attempted delivery by us.</li>
		</ol>
	</li>
	<li><strong>Payment</strong>
		<ol>
			<li>We take payment from your card at the time we receive your order, once we have checked your card details and stock availability. Goods are subject to availability. In the event that we are unable to supply the goods, we will inform you of this as soon as possible. A full refund will be given where you have already paid for the goods and if no goods have been already dispatched. Refund of payment does not apply to personalised, custom-made or custom fitted goods.</li>
			<li>While we try and ensure that all prices on our website are accurate, errors may occur. If we discover an error in the price of goods you have ordered we will inform you as soon as possible and give you the option of reconfirming your order at the correct price or cancelling it. If we are unable to contact you we will treat the order as cancelled. If you cancel and you have already paid for the goods, you will receive a full refund.</li>
			<li>Payment can be made by any method specified in Payment Methods. For information about secure on-line ordering see Privacy</li>
			<li>All prices include VAT (where applicable) at the applicable current rates but exclude delivery charges, unless expressly stated. (for further details including Express delivery charges see Shipping).</li>
		</ol>
	</li>
	<a name="returns"></a>
	<li><strong>Returns, Cancellations and Substitutions</strong>
		<ol>
			<li>We offer a 14 day money back guarantee, please refer to <a href="/tracker/help-support/returns/">Guarantees and Returns Policy</a>. Some products are excluded from the 14 Day Money Back Guarantee. These would normally include personalised products and more information in the Distance Selling Regulations Section. In addition, all Love Golf products are guaranteed against manufacturing defects for a minimum of 12 months. Your statutory rights are unaffected. Please note all shipping charges that have incurred prior cancellation of your order will be retained to cover costs if order has been cancelled for no reason or if user does not accept a replacement.</li>
			<li>Sometimes the product specifications from the manufacturer may change, in which case we will do our best to offer you a substitute of the same or better quality at the same price. If you are not happy with the replacement you can return it in accordance with our 14 day money back guarantee. Where applicable, you may cancel your order in accordance with your rights under the Distance Selling Regulations (see the <a href="/tracker/help-support/returns/">Guarantees and Returns Policy page</a> for further details). Please note any courier charges will be retained where the fault has not been or resulted from Love Golf.</li>
			<li>All sizes and measurements are approximate but we do try to make sure that they are as accurate as possible.</li>
			<li>Please note that NO REFUND will be passed for goods that are faulty or defective after the 14 Day Money Back Guarantee time. Love Golf will replace or exchange all faulty products available from the manufacturer, and if the identical size or model is no longer available then we will exchange for an equivalent make/model or offer you credit vouchers which can be used to purchase products from our website. See section 5.7 for information on how guarantees work on returned products.</li>
			<li>If you receive goods that you feel are not as stated, do not satisfy your requirements, or not up to your standards (for e.g. superficial marks on packaging or product, dust etc) we are happy to pass refund on the value of the goods if you have advised us of this within 14 days of delivery and only once we have received your goods back in its original condition. Please note that all delivery costs already incurred will be retained before passing refund. Please note that we offer a discounted shipping rate structure to offer you great value and in order to continue doing so we are unable to pass you full refund as the actual shipping cost will be retained before passing refund.</li>
			<li>Although every effort is made in checking all goods before dispatch, in some occasions incorrect or faulty goods may be received for which we do apologise for any inconveniences caused. Love Golf will assure that all such problems are solved and do request your co-operation in doing so. Once an incorrect or faulty delivery has been received it is your responsibility to complete the online returns procedure (after which further instructions will be emailed back) or to advise us of this within 7 working days after delivery. Once a return-request has been accepted, you are requested to send goods back to us (via your local post-office or courier or whichever more cost-effective). The return-shipping cost incurred to you will be settled in form of refund or credit vouchers only for the value of the shipping amount that you paid at time of ordering (as similarly operated when returned in-store). If the cost of sending goods back to us is reasonably high, then we do request you to contact us where we can assist in coming to an agreement to solve problem in a cost-effective manner for both parties. In some circumstances we may arrange a collection from your address once a collection charge has been accepted by yourself (available only within mainland U.K.). We will do our level best to compensate you for your costs in form of goods or gift vouchers, however we regret to advise you that we are unable to compensate you fully where the cost of return is not viable.</li>
			<li>Although we stock the best quality products, sometimes faults may be discovered after purchase. Love Golf offer a guarantee against manufacturer faults for a maximum of 1 year from the date of first delivery. Faulty products are required to be sent back for fault examination. If a genuine manufacturer fault is established, we will send the replacement that may be either repaired or exchanged. If an identical replacement is not available, we will offer an alternative product of similar value. However if for any reason you are not happy to take the replacement, we will offer you eVouchers that may be used to purchase goods from our website. To avoid doubt, all products exchanged, swapped, or purchased with eVouchers (only applies to vouchers issued from a return), will be guaranteed for only the balance of the initial 12 month period.</li>
			<li>All electric trolleys purchased from our website are covered by warranty only within the United Kingdom. Therefore if these products experience any defects or problems during operation whilst outside the United Kingdom, they will have to be sent back to us at your own cost where we will assess the problem and arrange for it to be fixed or replaced within the warranty period. A reshipping cost will be required for items to be shipped back out to you, which will be agreed prior dispatch.</li>
			<li>Most manufacturers will void the product warranty if it has been altered in any way. For example if the shaft of the club has been altered, or if the product has been altered without our consent. Due to the high technical nature of golf clubs, most manufacturers will only cover you against manufacturer defects if they have been customized by the manufacturer or through Love Golf. In our experience we have found that use of unauthorised fitting centres or inexperienced club-fitters could result in a poor quality product and therefore more likely to attain a defect.</li>
		</ol>
	</li>
	<li><strong>Liability and Indemnity</strong>
		<ol>
			<li>Nothing in these terms and conditions excludes or limits liability for death or personal injury caused by negligence, fraudulent misrepresentation, or any other liability which may not otherwise be limited or excluded under applicable law.</li>
			<li>Subject to Section 6.1 above, Love Golf will use reasonable endeavours to verify the accuracy of any information on the site but makes no representation or warranty of any kind express or implied statutory or otherwise regarding the contents or availability of the site or that it will be timely or error-free, that defects will be corrected, or that the site or the server that makes it available are free of viruses or bugs or represents the full functionality, accuracy, reliability of the website Love Golf will not be responsible or liable to you for any loss of content or material uploaded or transmitted through the website and Love Golf accepts no liability of any kind for any loss or damage from action taken or taken in reliance on material or information contained on the site.</li>
			<li>Subject to Section 6.1 above, other than as expressly provided in these terms and conditions with respect to specific products and except for the exclusive remedies set out at Section 5 above, any indemnities, warranties, terms and conditions (whether express or implied) are hereby excluded to the fullest extent permitted under applicable law.</li>
			<li>Subject to Section 6.1 above, Love Golf will not be liable, in contract, tort (including, without limitation, negligence), pre-contract or other representations (other than fraudulent on negligent misrepresentations) or otherwise out of or in connection with the terms and conditions for any:<br />* economic losses (including without limitation loss of revenues, data, profits, contracts, business or anticipated savings); or<br />* economic losses (including without limitation loss of revenues, data, profits, contracts, business or anticipated savings); or<br />* loss due to currency exchange-rate fluctuations (we take payment in British Sterling Pounds GBP and currency exchange rates fluctuate constantly in which case we cannot be held liable for loss of value in foreign currency during payment authorisations and refunds as value will remain the same in GBP Sterling Pounds ); or<br />* loss of goodwill or reputation; or<br />* special or indirect losses suffered or incurred by that party arising out of or in connection with the provisions of any matter under these terms and conditions.</li>
			<li>Notwithstanding the above, subject to Section 6.1 Love Golfs’ aggregate liability (whether in contract, tort or otherwise) for loss or damage shall in any event be limited to a sum equal to the amount paid or payable by you for the product(s) in respect of one incident or series of incidents attributable to the same clause.</li>
			<li>This clause 6 does not affect your statutory rights as a consumer, nor does it affect your contract cancellation rights.</li>
			<li>We will take all reasonable precautions to keep the details of your order and payment secure, but, unless we are negligent, we cannot be held liable for any losses caused as a result of unauthorised access to information provided by you.</li>
		</ol>
	</li> 
	<li><strong>Miscellaneous Provisions</strong>
		<ol>
			<li>The contract between us shall be governed by the laws of England and any dispute between us will be resolved exclusively in the courts of England. English is the only language offered for the conclusion of the contract.</li>
			<li>We have selected our products on the basis that they will be used for domestic use only, if you are planning to use them for business purposes please make sure that you are covered by appropriate insurance.</li>
			<li>Love Golf shall be under no liability for any delay or failure to deliver products or otherwise perform any obligation as specified in these terms and conditions if the same is wholly or partly caused whether directly or indirectly by circumstances beyond its reasonable control.</li>
			<li>To provide increased value to our customers, we may provide links to other websites or resources for you to access at your sole discretion. You acknowledge and agree that, as you have chosen to enter the linked website we are not responsible for the availability of such external sites or resources, and do not review or endorse and are not responsible or liable, directly or indirectly, for (i) the privacy practices of such websites, (ii) the content of such websites, including (without limitation) any advertising, content, products, goods or other materials or services on or available from such websites or resources or (iii) the use to which others make of these websites or resources, nor for any damage, loss or offence caused or alleged to be caused by, or in connection with, the use of or reliance on any such advertising, content, products, goods or other materials or services available on such external websites or resources.</li>
			<li>You may not assign or sub-contract any of your rights or obligations under these terms and conditions or any related order for products to any third party unless agreed upon in writing by Love Golf.</li>
			<li>Love Golf reserves the right to transfer, assign or sub-contract the benefit of the whole or part of any of its rights or obligations under these terms and conditions or any related contract to any third party.</li>
			<li>If any portion of these terms and conditions is held by any competent authority to be invalid or unenforceable in whole or in part, the validity or enforceability of the other sections of these terms and conditions shall not be affected.</li>
			<li>These terms and conditions do not create or confer any rights or benefits enforceable by any person that is not a party (within the meaning of the U.K. Contracts (Rights of Third Parties) Act 1999) except:<br />a) a person who is a permitted successor or assignee under Section 7.7 above of the rights or benefits of these terms and conditions may enforce such rights or benefits.<br />b) No consent from the persons referred to in Section 7.8 is required for the parties to vary or rescind these terms and conditions (whether or not in any way that varies or extinguishes rights or benefits in favour of such third parties).</li>
			<li>No delay or failure by Love Golf to exercise any powers, rights or remedies under these terms and conditions will operate as a waiver of them nor will any single or partial exercise of any such powers, rights or remedies preclude any other or further exercise of them. Any waiver to be effective must be in writing and signed by an authorised representative of Love Golf.</li>
			<li>These terms and conditions including the documents or other sources referred to in these terms and conditions supersede all prior representations understandings and agreements between you and Love Golf relating to the use of this website (including the order of products) and sets forth the entire agreement and understanding between you and Love Golf for your use of this website</li>
		</ol>
	</li>
</ol>
<p>&nbsp;</p>
<p>We recommend you print out a copy of these terms and conditions for your future reference.</p>
<p>&nbsp;</p>
<p>If you have any questions regarding the lovegolf.co.uk website please see the Customer Services section for more information and full contact details.</p>